# Generated by Django 4.2.4 on 2023-10-18 08:59

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_systemconfig_favicon_systemconfig_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="footer_column_1",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="footer_column_2",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="footer_column_3",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="footer_column_4",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="site_name",
            field=models.CharField(
                default="KM", max_length=100, verbose_name="Site name"
            ),
        ),
    ]
