# Generated by Django 4.2.4 on 2023-10-18 15:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0003_systemconfig_footer_column_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="footer_background",
            field=models.CharField(default="white", max_length=255),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="footer_end_line",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="footer_padding_bottom",
            field=models.IntegerField(default=20, help_text="in px"),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="footer_padding_side",
            field=models.IntegerField(default=20, help_text="in percent"),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="footer_padding_top",
            field=models.IntegerField(default=20, help_text="in px"),
        ),
    ]
