# Generated by Django 4.2.4 on 2023-10-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_systemconfig_footer_background_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                ("url", models.URLField(verbose_name="URL")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
        ),
    ]
