# Generated by Django 4.2.4 on 2023-10-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="header_background",
            field=models.CharField(default="white", max_length=255),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="header_fontcolor",
            field=models.CharField(default="white", max_length=255),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="header_fontsize",
            field=models.IntegerField(default=20, help_text="in px"),
        ),
    ]
