# Generated by Django 4.2.4 on 2023-11-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_systemconfig_header_background_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ["-order"]},
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=255),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
