# Generated by Django 4.2.4 on 2023-11-02 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_alter_menu_options_systemconfig_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ["order"]},
        ),
    ]
