# Generated by Django 4.2.4 on 2023-11-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="display_product",
            field=models.BooleanField(default=True),
        ),
    ]
