# Generated by Django 4.2.4 on 2024-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0011_systemconfig_home_page_background_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="business_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="business_header_cuisines",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="business_logo",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="image",
                verbose_name="business Logo",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
