# Generated by Django 4.1.13 on 2024-09-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0012_systemconfig_business_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(editable=False, max_length=8, unique=True)),
                ("hashed_key", models.CharField(editable=False, max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="A free-form name for the API key. Need not be unique. 50 characters max.",
                        max_length=50,
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Once API key expires, clients cannot use it anymore.",
                        null=True,
                        verbose_name="Expires",
                    ),
                ),
                ("is_connected", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoreConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_publish_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_secret_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paypal_client_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paypal_secret_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "notification_admin_emails",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated emails",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="collection_pre_order_days",
            field=models.IntegerField(
                default=0,
                help_text="How far in future customer can get his order. Set to zero if customer can order only for same day.",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="default_cooking_time",
            field=models.IntegerField(default=15, help_text="In minutes"),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="default_delivery_time",
            field=models.IntegerField(default=10, help_text="In minutes"),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="delivery_pre_order_days",
            field=models.IntegerField(
                default=3,
                help_text="How far in future customer can get his order. Set to zero if customer can order only for same day.",
            ),
        ),
    ]
