# Generated by Django 4.1.13 on 2024-10-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0013_apikey_coreconfig_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=255,
                    ),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("delivery_open_time", models.TimeField()),
                ("delivery_close_time", models.TimeField()),
                ("collection_open_time", models.TimeField()),
                ("collection_close_time", models.TimeField()),
                ("ordering_open_time", models.TimeField()),
                ("ordering_close_time", models.TimeField()),
            ],
            options={
                "verbose_name": "Schedule Configuration",
                "verbose_name_plural": "Schedule Configurations",
                "ordering": ["day"],
            },
        ),
    ]
