# Generated by Django 4.1.13 on 2024-10-18 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0014_scheduleconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("public_key", models.CharField(max_length=255, null=True)),
                ("app_id", models.CharField(max_length=255, null=True)),
                ("is_connected", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="APIKey",
        ),
    ]
