# Generated by Django 4.1.13 on 2024-10-30 17:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0016_device_firebase_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreconfig",
            name="firebase_service_account",
            field=models.FileField(
                help_text="Firebase service key file use for push notification",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="firebase_keys"
                ),
                upload_to="",
            ),
        ),
    ]
