# Generated by Django 4.2.4 on 2023-09-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0026_predefined_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributeoption",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Price",
            ),
        ),
    ]
