# Generated by Django 4.2.4 on 2023-09-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0027_attributeoption_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributeoption",
            name="key",
            field=models.CharField(default="", max_length=300),
        ),
    ]
