# Generated by Django 4.2.4 on 2023-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0028_attributeoption_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributeoption",
            name="key",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
