# Generated by Django 4.2.4 on 2023-11-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0029_alter_attributeoption_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
