# Generated by Django 4.2.4 on 2023-11-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0030_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="image",
                verbose_name="Image",
            ),
        ),
    ]
