# Generated by Django 4.2.4 on 2023-11-20 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0033_delete_basket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
