# Generated by Django 4.1.13 on 2025-05-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0034_remove_product_image_remove_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="price_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
