# Generated by Django 4.1.13 on 2024-07-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_tax_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest_phone_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Guest phone number"
            ),
        ),
    ]
