# Generated by Django 4.1.13 on 2024-08-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_order_guest_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest_first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="guest_last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
