# Generated by Django 4.1.13 on 2024-10-19 16:41

import django.utils.timezone
from django.db import migrations, models


def set_created_to_date_placed(apps, schema_editor):
    Order = apps.get_model("order", "Order")
    OrderLine = apps.get_model("order", "Line")

    for order in Order.objects.all():
        order.created = order.date_placed
        order.updated = order.date_placed
        order.status = 'Pending'
        order.save(update_fields=["created", "updated", "status"])

    OrderLine.objects.update(status="Pending")


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0017_order_created_at_order_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.RunPython(set_created_to_date_placed, reverse_code=migrations.RunPython.noop),
    ]
