# Generated by Django 4.1.13 on 2025-06-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0018_remove_order_created_at_remove_order_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="postcode",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Postcode"
            ),
        ),
    ]
