# Generated by Django 4.1.13 on 2025-06-08 19:33

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0020_alter_billingaddress_postcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaddress",
            name="postcode",
            field=oscar.models.fields.UppercaseCharField(
                blank=True, max_length=256, verbose_name="Post/Zip-code"
            ),
        ),
    ]
