# Generated by Django 4.1.13 on 2025-06-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0021_alter_billingaddress_postcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="postcode",
            field=models.CharField(default="", max_length=255, verbose_name="Postcode"),
        ),
    ]
