# Generated by Django 4.1.13 on 2025-06-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_billingaddress_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Postcode'),
        ),
    ]
