# Generated by Django 4.1.13 on 2025-06-20 21:49

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0008_alter_useraddress_postcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="postcode",
            field=oscar.models.fields.UppercaseCharField(
                blank=True, max_length=64, verbose_name="Post/Zip-code"
            ),
        ),
    ]
