# Generated by Django 4.1.13 on 2025-06-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0009_alter_useraddress_postcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="postcode",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="Postcode",
            ),
        ),
    ]
