# Generated by Django 4.2.4 on 2023-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0012_line_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="extra_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Extra Price",
            ),
        ),
    ]
