# Generated by Django 4.1.13 on 2024-06-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0003_auto_20181115_1953"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostcodeShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
