# Generated by Django 4.1.13 on 2024-06-20 12:33

from django.db import migrations


def create_default_shipping_rate(apps, schema_editor):
    PostcodeShippingRate = apps.get_model('shipping', 'PostcodeShippingRate')

    # Create the default shipping rate
    default_rate, created = PostcodeShippingRate.objects.get_or_create(
        rate=0.00,
        defaults={'code': 'DEFAULT'}
    )



class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0004_postcodeshippingrate"),
    ]

    operations = [
        migrations.RunPython(create_default_shipping_rate, reverse_code=migrations.RunPython.noop),
    ]
