# Generated by Django 4.1.13 on 2025-06-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_alter_postcode_code_alter_shippingzone_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
